### ISSUE TITLE
Use of LLVMSlicer

### ISSUE THREAD

**Issue by philbu** [jirislaby/LLVMSlicer#8]
Hi @jirislaby,

I'm nearly finished with upgrading your LLVMSlicer project to the LLVM version 4.0 and I will create a PR next week after some testing.

But here's my problem.
How am I supposed to use the slicer?
I'm using this command: 
  opt -load LLVMSlicer.so -create-hammock-cfg -slice-inter src.o -o dst.o
Afterwards I have an object file called dst.o but I'm not quite sure what it contains.
"The initial criteria considered here are all assert_fail function calls (which is effectively every
place where an assert is in the code)." 
Is code without "assert"s not sliced? Or can you slice code by any value you wish by simply using another command?

Thanks in advance for any help.

**Comment by Justme0** [comment]
By the way, another tool is also good: [https://github.com/mchalupa/dg/](https://github.com/mchalupa/dg/)
